---
# tasks file for unifi_controller
- name: include os dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: install dependencies
  apt:
    name: "{{ unifi_package_dependencies }}"
    state: present
    update_cache: yes

- name: install mongodb
  include_tasks: install-mongodb.yml

- name: install java packages
  apt:
    name: "{{ unifi_java_packages }}"
    state: "{{ unifi_install_state }}"
    update_cache: yes
  notify:
    - restart unifi

- name: install unifi
  include_tasks: install-unifi.yml

- name: update snappy java
  get_url:
    url: "{{ unifi_java_snappy_url }}"
    checksum: "{{ unifi_java_snappy_checksum }}"
    dest: "{{ unifi_java_snappy_file }}"
  notify:
    - restart unifi

- name: configure java for unifi
  lineinfile:
    create: yes
    path: '{{ unifi_config_file }}'
    regexp: '^JAVA_HOME='
    line: 'JAVA_HOME={{ unifi_java_home }}'
  notify:
    - restart unifi

- name: manage services
  service:
    name: "{{ item }}"
    state: "{{ unifi_services_state }}"
    enabled: "{{ unifi_services_enabled }}"
  with_items: "{{ unifi_services }}"
